version: '3.1'

services:
  zoo1:
    image: zookeeper:3.5.7
    restart: unless-stopped
    hostname: zoo1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - messages-network
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka1:
    restart: unless-stopped
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    networks:
      - messages-network
    environment:
      CREATE_TOPICS: "messages:1:1"
      KAFKA_LISTENERS: LISTENER_BOB://kafka1:29092,LISTENER_FRED://kafka1:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka1:29092,LISTENER_FRED://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zoo1

  kafdrop:
    restart: unless-stopped
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    networks:
      - messages-network
    environment:
      KAFKA_BROKERCONNECT: kafka1:29092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication"
    depends_on:
      - kafka1

  spark:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 8080:8080
      - 7077:7077
    depends_on:
      - kafdrop
      
  spark-worker-1:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark
  spark-worker-2:
    image: bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    depends_on:
      - spark

  spark-notebook:
    image: jupyter/pyspark-notebook
    ports:
      - 10000:8888
    depends_on:
      - spark

networks:
  messages-network:
    driver: bridge