# This is a basic workflow that is manually triggered

name: Requirements uploader

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master
    paths:
      - 'requirements.txt'
      - 'conda_requirements.txt'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    name: Deploy to GCS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_UPLOADER }}
          BUCKET_NAME: ${{ secrets.GCP_STORAGE_BUCKET_NAME }}
        with:
          args: cp requirements.txt conda_requirements.txt gs://$BUCKET_NAME/
          cli: gsutil
